name: Build NDEF Emulator APKs

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build Phone and Watch APKs
        run: |
          ./gradlew clean assemblePhoneDebug assembleWatchDebug
          
      - name: Upload Compiled APKs
        uses: actions/upload-artifact@v4
        with:
          name: ndef-emulator-apks
          path: "**/build/outputs/apk/**/*.apk"
